# -*- coding: utf-8 -*-
"""画布参数区（View 页签）补充英文对照表。

``_panel.py`` 里的 ``_CV_EN`` 是历史累积的对照表；本文件是它的增量，键为界面上的
中文原文，由 ``set_lang`` → ``apply_text_map`` 整树套用（见 molstudio/ui/i18n_utils.py）。
注：键是从运行中的界面自动导出的，与界面文字逐字一致。
"""

CV_EN_EXTRA = {
    'ACES 胶片曲线：高光滚降不再死白，中间调轻微提亮': 'ACES filmic curve: highlight roll-off stops clipping to white and mid-tones are lifted slightly',
    'AO 采样半径（像素，4 – 32）': 'AO sample radius (pixels, 4 – 32)',
    'Blinn-Phong 经典': 'Blinn-Phong (classic)',
    'Blue/Orange shiny  — 柔和 (蓝/橙)': 'Blue/Orange shiny  — soft (blue/orange)',
    'Clear-coat 清漆': 'Clear-coat',
    'Cyan/Magenta shiny  — 柔和 (青/品红)': 'Cyan/Magenta shiny  — soft (cyan/magenta)',
    'GGX 微表面': 'GGX microfacet',
    'Gaussview default  — Gaussview 默认外观 (o* = 0.8/0.7/0.7/-0.5)': 'Gaussview default  — GaussView default look (o* = 0.8/0.7/0.7/-0.5)',
    'IGMH 片段式：Shift+左键拖框框选原子归入片段（增量），vdW 外壳只画片段内的原子。片段集合持久保留——清除画布选中、取消高亮都不影响已加的壳；右键菜单或「清除」按钮可清空片段': 'IGMH fragment mode: hold Shift and drag a box to assign atoms to the fragment set (additive); the vdW shell then draws only atoms inside the fragment set. The set persists — clearing the canvas selection or the highlight does not remove shells you added; the right-click menu or the 「Clear」 button empties it',
    'Matcap 材质球': 'Matcap sphere',
    'Matcap 材质球预设（仅 Matcap 材质球模型生效）：\n· 柔和影棚 — 柔和漫反射 + 轻微高光\n· 亮面塑料 — 强烈锐利高光\n· 哑光陶瓷 — 无高光的柔和哑光\n· 金属 — 高对比 + 边缘反光': 'Matcap sphere presets (only apply to the Matcap material):\n· Soft studio — soft diffuse + subtle specular\n· Glossy plastic — strong, sharp highlights\n· Matte ceramic — soft matte with no highlight\n· Metal — high contrast + edge reflections',
    'Mono Cyan shiny  — 柔和 (单色青)': 'Mono Cyan shiny  — soft (mono cyan)',
    'Orange/Blue shiny  — 柔和 (橙/蓝)': 'Orange/Blue shiny  — soft (orange/blue)',
    'Purple/Yellow shiny  — 柔和 (紫/黄)': 'Purple/Yellow shiny  — soft (purple/yellow)',
    'Red/Green shiny  — 柔和 (红/绿)': 'Red/Green shiny  — soft (red/green)',
    'Teal/Rose shiny  — 柔和 (青绿/玫红)': 'Teal/Rose shiny  — soft (teal/rose)',
    'VESTA (VESTA 配色)': 'VESTA (VESTA palette)',
    'WBOIT 深度衰减强度：\n· 数值越大 → 越靠前的等值面占比越高，越通透。\n· 数值越小 → 前后等权，后层（经雾化的偏亮片元）掺得越多，整体偏暗。\n默认 4.0。': 'WBOIT depth-weight attenuation:\n· Larger values → front isosurfaces dominate, making them more transparent.\n· Smaller values → front and back are weighted equally, so the (fogged, brighter) rear layers blend in more and the image gets darker.\nDefault 4.0.',
    'WBOIT 深度衰减（0.0 – 12.0，越大越通透）': 'WBOIT depth attenuation (0.0 – 12.0, larger = more transparent)',
    'WBOIT 衰减:': 'WBOIT attenuation:',
    'WBOIT（加权混合，单趟）': 'WBOIT (weighted blended, single pass)',
    'amber-glass  — Amber × Cobalt Blue Glass (琥珀金×钴蓝)': 'amber-glass  — Amber × Cobalt Blue Glass (amber × cobalt blue)',
    'aurora-pearl  — Aurora Pearl, Iridescent Teal-Violet (极光珍珠)': 'aurora-pearl  — Aurora Pearl, Iridescent Teal-Violet (aurora pearl)',
    'copper-patina  — Copper × Patina Teal, Oxidized Metal (铜绿氧化)': 'copper-patina  — Copper × Patina Teal, Oxidized Metal (oxidized copper)',
    'crystal-glass  — Cream × Lavender Crystal Glass (暖奶×冷薰水晶璃)': 'crystal-glass  — Cream × Lavender Crystal Glass (warm cream × cool lavender)',
    'frost-glass  — Mint × Coral Frosted Glass (薄荷×珊瑚磨砂璃)': 'frost-glass  — Mint × Coral Frosted Glass (mint × coral frosted glass)',
    'ghost-glass  — Ghost Glass, Ethereal Ice Translucent (幽灵冰晶)': 'ghost-glass  — Ghost Glass, Ethereal Ice Translucent (ghost ice crystal)',
    'hologram  — Hologram, Silver Rainbow Sheen (全息幻彩)': 'hologram  — Hologram, Silver Rainbow Sheen (holographic sheen)',
    'jade-glass  — Emerald × Ruby Glass (翡翠×红宝石璃)': 'jade-glass  — Emerald × Ruby Glass (jade × ruby glass)',
    'liquid-quantum  — Liquid Quantum, Fluid Glass (液态量子)': 'liquid-quantum  — Liquid Quantum, Fluid Glass (liquid quantum)',
    'matte-clay  — Studio Clay, Terracotta × Slate Matte (陶土哑光)': 'matte-clay  — Studio Clay, Terracotta × Slate Matte (terracotta matte)',
    'neon-cyber  — Neon Cyber, Electroluminescent Tube (霓虹赛博)': 'neon-cyber  — Neon Cyber, Electroluminescent Tube (neon cyber)',
    'plasma-core  — Plasma Core, Indigo-Orange Energy (等离子核心)': 'plasma-core  — Plasma Core, Indigo-Orange Energy (plasma core)',
    'plastic-bright  — Plastic / Glossy Bright Surface (亮面塑料)': 'plastic-bright  — Plastic / Glossy Bright Surface (glossy plastic)',
    'precision-ink  — Precision Ink, Publication Minimal (精密墨稿)': 'precision-ink  — Precision Ink, Publication Minimal (precise ink)',
    'quantum-crystal  — Quantum Crystal, Prismatic Solid (量子晶体)': 'quantum-crystal  — Quantum Crystal, Prismatic Solid (quantum crystal)',
    'quantum-porcelain  — Quantum Porcelain, Smooth Enamel (量子瓷釉)': 'quantum-porcelain  — Quantum Porcelain, Smooth Enamel (quantum porcelain)',
    'rose-gold  — Rose Gold × Champagne, Brushed Metal (玫瑰金香槟)': 'rose-gold  — Rose Gold × Champagne, Brushed Metal (rose gold champagne)',
    'ultra-glass  — Ice Crystal, Ultra-Transparent Glass (冰晶透澈)': 'ultra-glass  — Ice Crystal, Ultra-Transparent Glass (ice crystal, ultra clear)',
    'vdW 外壳不透明度（0.02 ~ 0.80，越小越透明）': 'vdW shell opacity (0.02 ~ 0.80, smaller = more transparent)',
    'vdW 外壳描边粗细（0.01 ~ 0.60 剪影带厚度，越大越粗）': 'vdW shell outline width (0.01 ~ 0.60 silhouette band thickness, larger = thicker)',
    'vdW 球面剪影描边（独立于原子描边，单独控制）': 'vdW sphere silhouette outline (independent of the atom outline)',
    'velvet-quantum  — Velvet Quantum, Soft Matte (天鹅绒量子)': 'velvet-quantum  — Velvet Quantum, Soft Matte (velvet quantum)',
    '「一律单键」：检测到的键全部画成实线单键；\n「按键长自动判定」：用键长与单键共价半径和的比值推出\n单键 / 离域键(1.5) / 双键 / 三键（只对 C/N/O 之间的键生效）。\n右键逐键指定的键型优先于本模式': '「All single bonds」: every detected bond is drawn as a solid single bond;\n「Auto by bond length」: single / delocalized (1.5) / double / triple bonds are inferred from the bond length relative to the sum of single-bond covalent radii (C/N/O bonds only).\nPer-bond types set via right-click take precedence over this mode',
    '一次展开/折叠全部设置分节（状态会记住，下次打开这个界面沿用）': 'Expand/collapse all setting sections at once (the state is remembered for next time)',
    '交换正/负相位颜色（等价 IboView 翻转相位，几何不变）': "Swap the positive/negative phase colors (equivalent to IboView's phase flip; geometry unchanged)",
    '亮面塑料': 'Glossy plastic',
    '从 JSON 文件载入样式并应用': 'Load a style from a JSON file and apply it',
    '元素半径': 'Element radii',
    '元素颜色…': 'Element colors…',
    '光泽 / 镜面高光强度（0.00 – 1.00）': 'Gloss / specular highlight strength (0.00 – 1.00)',
    '光泽（镜面高光强度）': 'Gloss (specular highlight strength)',
    '光照/渲染效果（独立于原子配色）：IboView 三光 / MolViewer 单光 / 双光 / 四光': 'Lighting / render effect (independent of atom colors): IboView three-light / MolViewer one-, two- and four-light',
    '关闭后远处原子/轨道不再因景深变淡发白': 'When off, distant atoms or orbitals no longer fade toward white with depth',
    '剥离层数:': 'Peel layers:',
    '勾选后在每个原子球面画两条交叉的大圆环（十字效果）；未勾选则完全不显示': 'When ticked, two crossing great circles are drawn on every atom sphere (crosshair effect); unticked hides them completely',
    '勾选后按 IboView IsoThreshold 语义取等值面：\n选取使 |data| 累积权重达到指定百分比的等值面。\n取消勾选则使用下方的绝对 isovalue（cube 文件原始单位）。': "When ticked, the isosurface follows IboView's IsoThreshold semantics:\npick the surface at which the cumulative |data| weight reaches the given percentage.\nUnticked uses the absolute isovalue below (raw cube units).",
    '勾选后由色轮控制正/负相位颜色；否则沿用样式默认配色': "When ticked, the color wheel controls the positive/negative phase colors; otherwise the style's default palette is kept",
    '半球环境光强度（0..1，越大补光越亮）': 'Hemisphere light intensity (0..1, larger = brighter fill)',
    '半球环境光强度（0.00 – 1.00，越大补光越亮）': 'Hemisphere light intensity (0.00 – 1.00, larger = brighter fill)',
    '半球环境光的地面色（法线朝下时取此色）': 'Hemisphere light ground color (taken when the normal points down)',
    '半球环境光的天顶色（法线朝上时取此色）': 'Hemisphere light sky color (taken when the normal points up)',
    '半球环境光（Hemisphere Lighting）：按世界空间法线的朝上/朝下程度，\n在「天顶色」与「地面色」之间插值，作为廉价的环境漫反射补光。\n只叠加到 RGB，不参与 GGX 镜面项，也不改变透明度（兼容 WBOIT）。': 'Hemisphere lighting: interpolates between the sky and ground colors according to how much the world-space normal points up or down, as a cheap ambient diffuse fill.\nIt is added to RGB only, does not feed the GGX specular term, and does not change opacity (WBOIT-compatible).',
    '单独调节当前结构里每个元素原子球的半径倍率（0.2–4.0）\n只改变显示球径，不改坐标与键长判定': 'Adjust the sphere-radius scale of each element in the current structure (0.2–4.0).\nOnly the drawn sphere size changes; coordinates and bond perception are unaffected',
    '原子按元素配色方案（独立于光照），只改颜色不改材质': 'Atom coloring scheme by element (independent of lighting); changes colors only, not materials',
    '哑光陶瓷': 'Matte ceramic',
    '在正常球棍模型之上叠加半透明范德华半径球壳（元素色，体现空间包围）': 'Overlay translucent van der Waals shells on the normal ball-and-stick model (element colors, showing spatial enclosure)',
    '在等值面剪影边缘叠加细描边（颜色由 MolViewer 预设或默认深色决定）': 'Add a thin outline along the isosurface silhouette (color from the MolViewer preset or a default dark tone)',
    '屏幕空间遮蔽：凹槽、原子与等值面接触处变暗，立体感的主要来源': 'Screen-space occlusion: crevices and atom/isosurface contacts darken — the main source of depth',
    '开启后原子直接以范德华半径（Bondi 1964 表）显示，而非默认绘制半径': 'When on, atoms are drawn at their van der Waals radii (Bondi 1964 table) instead of the default drawing radii',
    '弹出光源控制面板：左侧球体实时预览光点，右侧调整数量/方向/光晕': 'Open the light control panel: live preview of the light dots on the left, count/direction/glow on the right',
    '弹出圆环控制面板：调两条环的方位角/俯仰角；勾选锁定后分子怎么转圆环都不转': 'Open the ring control panel: set azimuth/elevation for both rings; when locked, the rings stay put while the molecule rotates',
    '恢复样式默认配色': "Restore the style's default palette",
    '把当前样式（配色/光照/描边/透明度/相位色等）保存为 JSON 文件': 'Save the current style (colors / lighting / outline / opacity / phase colors …) to a JSON file',
    '把输入框里的原子加入 vdW 片段并显示外壳': 'Add the atoms from the input box to the vdW fragment set and show the shell',
    '拖动旋转色轮：转一圈循环改变等值面配色': 'Drag to rotate the color wheel: a full turn cycles the isosurface palette',
    '按可见边界（瓣与瓣、等值面与原子）压暗的强度': 'Darkening strength along visible boundaries (lobe-to-lobe, isosurface-to-atom)',
    '排序混合（画家算法）': "Sorted blending (painter's algorithm)",
    '整帧先按倍率放大离屏渲染再降采样（超采样抗锯齿）。\n实时画布没有 MSAA，且 MSAA 对半透明等值面无效，故用这种方式；\n开销按倍率平方增长，卡顿时降到 1.0× 或关闭。': 'The whole frame is first rendered off-screen at the given multiplier and then downsampled (supersampling anti-aliasing).\nThe live canvas has no MSAA, and MSAA does not work for translucent isosurfaces, hence this approach;\ncost grows with the square of the multiplier — drop it to 1.0× (or turn it off) if the view feels slow.',
    '明暗交界线柔化（0..1）：\n· 0（默认）— 标准 Lambert，与原本完全一致，明暗交界较锐利\n· 1 — Half-Lambert，背光侧也受光，交界最柔和\n单光源斜射时等值面的硬边就是 terminator，拖大它可柔化。\n只影响漫反射，高光位置/形状不变。': "Terminator softening (0..1):\n· 0 (default) — standard Lambert, identical to the previous look; the light/dark boundary is fairly sharp\n· 1 — Half-Lambert; the shadow side also receives light and the transition is softest.\nWith a single oblique light the isosurface's hard edge is the terminator — raise this to soften it.\nAffects diffuse only; the highlight's position and shape are unchanged.",
    '明暗交界线柔化（0.00 – 1.00，0 = 标准 Lambert）': 'Terminator softening (0.00 – 1.00, 0 = standard Lambert)',
    '景深雾化强度（远处向背景色淡出）：\n0.6 = 场景最深处融入背景 60%，1.0 = 完全融入，最大 2.0（更强的空气透视）': 'Depth-fog strength (distant parts fade into the background):\n0.6 = the deepest part blends 60% into the background, 1.0 = fully blended, max 2.0 (stronger aerial perspective)',
    '暗化向物体内侧铺开的宽度（像素）：小=细轮廓，大=柔和阴影': 'Width over which the darkening spreads inward (pixels): small = thin contour, large = soft shadow',
    '柔和影棚': 'Soft studio',
    '次表面散射强度（0.00 – 1.00，0 = 关闭）': 'Subsurface scattering strength (0.00 – 1.00, 0 = off)',
    '次表面散射强度（0=关闭，走标准 Lambert）：\n·  softening —— 明暗交界向背光侧推移，过渡拉长，玉/蜡般的柔和\n·  背光透射 —— 逆光时边缘透光发亮，掠射处更明显\n对所有多灯模型生效；Matcap 材质球替代了光照，故对其无效': 'Subsurface scattering (0 = off, standard Lambert):\n· softening — the terminator moves toward the shadow side and the transition lengthens, giving a jade/wax-like softness\n· back-lit transmission — edges glow when back-lit, most visible at grazing angles\nApplies to all multi-light models; the Matcap sphere replaces lighting, so it has no effect there',
    '深度剥离趟数上限（1-8，默认 4）：\n越多层交叠越精确，开销随趟数线性增长。': 'Maximum number of depth-peeling passes (1–8, default 4):\nmore passes resolve more overlapping layers; the cost grows linearly with the number of passes.',
    '深度剥离（多趟）': 'Depth peeling (multi-pass)',
    '清漆层强度（0.00 – 2.00，越大清漆高光越亮）': 'Clear-coat strength (0.00 – 2.00, larger = brighter clear-coat highlight)',
    '清漆层强度：越大清漆高光越亮。仅对 Clear-coat 清漆生效': 'Clear-coat strength: larger values give a brighter clear-coat highlight. Only applies to the Clear-coat material',
    '清漆层粗糙度（0.03 – 1.00，越小清漆高光越锐）': 'Clear-coat roughness (0.03 – 1.00, smaller = sharper clear-coat highlight)',
    '清漆层粗糙度：越小清漆高光越锐。仅对 Clear-coat 清漆生效': 'Clear-coat roughness: smaller values give a sharper clear-coat highlight. Only applies to the Clear-coat material',
    '清空 vdW 片段原子集合；「仅选中片段」模式下外壳随之消失，可重新输入或框选添加': 'Clear the vdW fragment set; in 「selected fragment only」 mode the shell disappears with it, and you can add atoms again by typing indices or box-selecting',
    '点击选择正相位等值面颜色': 'Click to pick the positive-phase isosurface color',
    '点击选择负相位等值面颜色': 'Click to pick the negative-phase isosurface color',
    '环境光遮蔽强度（0 = 关闭，同时省掉深度预通道）': 'Ambient occlusion strength (0 = off, which also skips the depth pre-pass)',
    '生成轨道 cube 的网格密度：1=稀疏，2=中等，3=精细': 'Grid density for the orbital cube: 1 = coarse, 2 = medium, 3 = fine',
    '画面四角轻微压暗，视线收拢到中心': 'Slight vignetting towards the corners draws the eye to the center',
    '百分比:': 'Percent:',
    '直接输入不透明度（0.02 ~ 0.80，回车生效）': 'Type an exact opacity (0.02 ~ 0.80), press Enter to apply',
    '直接输入描边带厚度（0.01 ~ 0.60，回车生效）': 'Type an exact outline band thickness (0.01 ~ 0.60), press Enter to apply',
    '相对阈值 (80%)': 'Relative threshold (80%)',
    '等值面描边粗细（0.01 – 0.99，窄带阈值宽度）': 'Isosurface outline width (0.01 – 0.99, narrow-band threshold width)',
    '等值面背面调暗（0.10 – 1.00）：\n· 1.00 — 关闭，正反面同亮（旧画面）\n· 0.80（默认）— 背面比正面暗 20%，半透明波瓣读出厚度/体积感\n只影响双面渲染的轨道等值面；原子球/键为单面材质，不受影响。': 'Back-face darkening for isosurfaces (0.10 – 1.00):\n· 1.00 — off; front and back faces are equally bright (the old look)\n· 0.80 (default) — the back face is 20% darker, so translucent lobes read as having thickness/volume\nOnly affects double-sided orbital isosurfaces; atom spheres and bonds use single-sided materials and are unaffected.',
    '等值面背面调暗（0.10 – 1.00，1.00 = 关闭）': 'Back-face darkening for isosurfaces (0.10 – 1.00, 1.00 = off)',
    '等值面透明度：0% = 完全不透明，100% = 完全透明。\nVESTA / CYLview / MolStudio 三个样式为线性（滑块值即表面 alpha）；\n其余样式的半透明观感沿用 IboView 的光照调制（亮处实、暗处虚）。': "Isosurface opacity: 0% = fully opaque, 100% = fully transparent.\nThe VESTA / CYLview / MolStudio styles are linear (the slider value is the surface alpha);\nthe other styles keep IboView's lighting-modulated translucency (solid where lit, faint where dark).",
    '粗糙度（0.03 – 1.00，越小越镜面）': 'Roughness (0.03 – 1.00, smaller = more mirror-like)',
    '粗糙度（底层高光斑点大小）：越小越镜面、光点越集中。对 GGX 微表面与 Clear-coat 清漆生效': 'Roughness (size of the underlying highlight speckle): smaller = more mirror-like and a tighter highlight. Applies to the GGX microfacet and Clear-coat materials',
    '线性空间光照（B 方案）：\n· 颜色先转线性再计算光照，透明混合（等值面叠加/雾化/描边）\n  全程线性域，最后统一转回 sRGB 显示\n· 半透明等值面的叠加不再发灰/发奶，正负瓣交界更饱和\n· 中间调整体会略微变亮（gamma 响应变化，属正常现象）\n· 关闭 = sRGB 直通，与旧版观感完全一致': 'Linear-space lighting (option B):\n· colors are converted to linear before lighting, and blending (isosurface stacking / fog / outline) stays in linear space, converting back to sRGB for display\n· translucent isosurfaces no longer stack to a grey/milky look and phase boundaries are more saturated\n· mid-tones get slightly brighter (a change in gamma response — expected)\n· off = straight sRGB, identical to the previous look',
    '缩放范德华半径（Bondi 表值 × 比例），对原子与外壳同时生效': 'Scale van der Waals radii (Bondi table value × factor); applies to atoms and shells alike',
    '自定义每种元素的原子颜色（覆盖默认 CPK 配色）': 'Customize the atom color of each element (overrides the default CPK palette)',
    '见左侧说明；自动判定把 C=C / C=O / C≡C / 芳香环等按几何画成双键 / 三键 / 离域键': 'See the note on the left; auto detection draws C=C / C=O / C≡C / aromatic rings as double / triple / delocalized bonds from the geometry',
    '设置导出/预览的背景颜色': 'Set the background color for export/preview',
    '设置等值面描边颜色（默认黑色）': 'Set the isosurface outline color (black by default)',
    '调节化学键颜色与材质（光泽 / 面亮度）': 'Adjust bond color and material (gloss / face brightness)',
    '超采样倍率（1.0× = 不做超采样）': 'Supersampling multiplier (1.0× = no supersampling)',
    '输入要加 vdW 外壳的原子编号（1-based），支持逗号分隔与范围，如 1-12,15；点「vdW」按钮应用到画布。与 Shift+框选归入的是同一个片段集合': 'Atom indices to give a vdW shell (1-based); commas and ranges are accepted, e.g. 1-12,15. Click 「vdW」 to apply to the canvas. This is the same fragment set used by Shift+box selection',
    '选中原子时的标记形状：\n· 包裹（默认）— 贴合原子表面的一层半透明高亮壳，配合原子本体染色。\n· 透明球 — 更大的半透明球。\n· 圆环 — 环绕原子的环。\n· 光晕 — 内壳 + 大范围外壳。\n（早期版本的「二十面体」已移除：离原子太远、边角生硬。）': 'Marker shape for selected atoms:\n· Wrap (default) — a translucent highlight shell hugging the atom surface, tinted together with the atom.\n· Transparent ball — a larger translucent sphere.\n· Ring — a ring around the atom.\n· Halo — inner shell + a wide outer shell.\n(The early 「icosahedron」 marker was removed: it sat too far from the atom and had hard edges.)',
    '选中标记半径 ±12% 正弦呼吸动画': 'Selection marker radius breathes ±12% (sine animation)',
    '选择等值面正/负相位配色方案（移植自 IboView）': 'Choose the positive/negative phase palette for isosurfaces (ported from IboView)',
    '透明合成:': 'Blending:',
    '透明度 0-100%（精确输入）': 'Opacity 0-100% (exact input)',
    '透明等值面的合成方式：\n· WBOIT — 单趟渲染，按深度与不透明度加权累加（McGuire & Bavoil 2013），本项目自研路径，开销恒定。\n· 深度剥离 — 多趟逐层剥离（Everitt 2001，本项目独立实现），合成最精确，开销随层数线性增长。\n· 排序混合 — 按三角形深度从远到近绘制，最省资源，复杂轨道可能出现穿插错误。\n所选模式不可用时自动回退到另一种。': "How translucent isosurfaces are composited:\n· WBOIT — single pass, weighted accumulation by depth and opacity (McGuire & Bavoil 2013), this project's own path with constant cost.\n· Depth peeling — multi-pass layer-by-layer peeling (Everitt 2001, implemented independently here); the most accurate compositing, with cost growing linearly in the number of layers.\n· Sorted blending — draws triangles back-to-front; the cheapest, but complex orbitals may show sorting artifacts.\nIf the selected mode is unavailable the renderer falls back to another one.",
    '采样环半径（屏幕像素）。分子越密集、想要越宽的接触阴影就调大': 'Sample-ring radius (screen pixels). Increase it for denser molecules or wider contact shadows',
    '重置相机视角（居中并铺满分子/等值面）': 'Reset the camera view (center and fit the molecule/isosurface)',
    '重置视角': 'Reset view',
    '金属': 'Metal',
    '键样式': 'Bond style',
    '镜面/光照模型（原子与等值面统一生效）：\n· GGX 微表面 — 现代，散射尾宽、边缘有菲涅尔提亮（玻璃/珠光感）\n· Blinn-Phong 经典 — 双瓣高光（宽高光 + 中心亮点）\n· Clear-coat 清漆 — 柔和底层 + 尖锐清漆层，上釉/湿面感\n· Matcap 材质球 — 法线查材质球贴图，观感由预设贴图决定': 'Specular / lighting model (applies to atoms and isosurfaces alike):\n· GGX microfacet — modern; wide scattering tail and Fresnel brightening at the edges (glass/pearl feel)\n· Blinn-Phong (classic) — two-lobe highlight; see the classic references for the exact shape',
}
